name: deploy-release-apk

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Deploy Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          java-package: jdk
          architecture: x86

      - name: Grant permission to gradlew
        run: chmod +x gradlew

      - name: Assemble release with Gradle
        run: ./gradlew assembleRelease

      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Change artifact name
        run: mv ${{steps.sign_app.outputs.signedReleaseFile}} app/build/outputs/apk/release/SyosetuViewer.apk

      - name: Deploy artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            app/build/outputs/apk/release/SyosetuViewer.apk
